[package]
title = "V-HACD Convex Decompostion"
description="V-HACD Convex Decompostion"
version = "106.0.20"
authors = ["NVIDIA"]
repository = ""
keywords = ["convex", "convexdecomposition"]
category = "simulation"
icon = "data/icon.png"
preview_image = "data/preview.png"
changelog="docs/CHANGELOG.md"
readme  = "docs/README.md"
support_level = "Enterprise"

[package.writeTarget]
kit = true
python = true
usd = true

[dependencies]
"omni.assets.plugins" = {}
"omni.usd.libs" = {}
"omni.usd.schema.physx" = {}
"omni.kit.commands" = {optional=true}

[[python.module]]
name = "omni.convexdecomposition"

[[native.plugin]]
path = "bin/*.plugin"
