[package]
title = "PhysX Vehicle"
description="Exposes PhysX vehicle authoring capability, default input control and samples."
repository = ""
keywords = ["physics", "physx", "vehicle"]
category = "simulation"
authors = ["NVIDIA"]

version = "106.0.20"

icon = "data/icon.png"
preview_image = "data/preview.png"
changelog="docs/CHANGELOG.md"
readme  = "docs/README.md"

support_level = "Example"

[package.writeTarget]
kit = true
python = true
usd = true

[dependencies]
"omni.ui" = {}
"omni.kit.window.property" = {}
"omni.physx" = {}
"omni.kit.property.physx" = {}  # note: to make sure vehicle property widgets show after physx core widgets
"omni.physx.demos" = {}
"omni.physx.ui" = {}

[[python.module]]
name = "omni.physxvehicle"

[[native.plugin]]
path = "bin/*.plugin"

[[test]]
dependencies = [
   "omni.kit.renderer.core",
]
waiver = "PhysX tests are running in a separate CI pipeline. Tests are in separate extensions."