[core]
reloadable = true
order = 0

[package]
version = "1.7.0"
category = "Simulation"
title = "Generate Extension"
description = "UI tool for generating extension templates for different common workflows"
authors = ["NVIDIA"]
repository = ""
keywords = []
changelog = "docs/CHANGELOG.md"
readme = "docs/README.md"
icon = "data/icon.png"
preview_image = "data/preview.png"


[dependencies]
"omni.kit.uiapp" = {}
"omni.isaac.ui" = {}
"omni.isaac.core" = {}
"omni.isaac.nucleus" = {}

[[python.module]]
name = "omni.isaac.extension_templates"
