[package]
title = "PhysX Cooking"
description="PhysX 5 mesh cooking system."

version = "106.0.20"
authors = ["NVIDIA"]

repository = ""
keywords = ["physics", "physx", "cooking"]
category = "simulation"

icon = "data/icon.png"
preview_image = "data/preview.png"
changelog="docs/CHANGELOG.md"
readme  = "docs/README.md"

support_level = "Enterprise"

[package.writeTarget]
kit = true
python = true
usd = true

[dependencies]
"omni.convexdecomposition" = { version = "106.0.20", exact = true }
"omni.localcache" = { version = "106.0.20", exact = true }
"omni.usd.libs" = {}
"omni.usd.schema.physx" = { version = "106.0.20", exact = true }
"omni.usdphysics" = { version = "106.0.20", exact = true }
"omni.physx.foundation" = { version = "106.0.20", exact = true }

[[python.module]]
name = "omni.physxcooking"

[[native.plugin]]
path = "bin/omni.physx.cooking.plugin"

[[test]]
waiver = "PhysX tests are running in a separate CI pipeline. Tests are in separate extensions."
