[core]
reloadable = true
order = 0

[package]
version = "1.0.0"
category = "Simulation"
title = "ConveyorObjectSceneGen"
description = "This extension loads in a scene with teeth oriented in random positions and orientations over a conveyor belt. A UR5e is loaded in as well. The scene features 3 actions graphs that will pass the camera and joint states as topics."
authors = ["NVIDIA"]
repository = ""
keywords = []
changelog = "docs/CHANGELOG.md"
readme = "docs/README.md"
preview_image = "data/preview.png"
icon = "data/icon.png"


[dependencies]
"omni.kit.uiapp" = {}
"omni.isaac.ui" = {}
"omni.isaac.core" = {}
"omni.isaac.ros2_bridge" = {}

[[python.module]]
name = "ConveyorObjectSceneGen_python"