#displayed application name
name = "Isaac Sim"
#displayed before application name in launcher
productArea = "Omniverse"
version = "4.1.0"

#unique identifier for component, all lower case, persists between versions
slug = "isaac-sim"
## install and launch instructions by environment
[defaults.windows-x86_64]
url = ""
entrypoint = "${productRoot}/isaac-sim.selector.bat"
args = []

[defaults.windows-x86_64.environment]

[defaults.windows-x86_64.install]
pre-install = ""
pre-install-args = []
install = ""
install-args = []
post-install = "${productRoot}/omni.isaac.sim.post.install.bat"
post-install-args = ""

[defaults.windows-x86_64.uninstall]
pre-uninstall = ""
pre-uninstall-args = []
uninstall = ""
uninstall-args = []
post-uninstall = ""
post-uninstall-args = []

[defaults.linux-x86_64]
url = ""
entrypoint = "${productRoot}/isaac-sim.selector.sh"
args = []
[defaults.linux-x86_64.environment]

[defaults.linux-x86_64.install]
pre-install = ""
pre-install-args = []
install = ""
install-args = []
post-install = "${productRoot}/omni.isaac.sim.post.install.sh"
post-install-args = ""

[defaults.linux-x86_64.uninstall]
pre-uninstall = ""
pre-uninstall-args = []
uninstall = ""
uninstall-args = []
post-uninstall = ""
post-uninstall-args = []
