[cloner]
reloadable = true
order = 0

[package]
version = "0.8.1"
category = "Simulation"
title = "Isaac Sim Cloner"
description = "Cloner"
authors = ["NVIDIA"]
repository = ""
keywords = ["isaac"]
changelog = "docs/CHANGELOG.md"
readme = "docs/README.md"
icon = "data/icon.png"
preview_image = "data/preview.png"
writeTarget.kit = true

[dependencies]
"omni.usd" = {}
"omni.usd.libs" = {}
"omni.physx" = {}
"omni.isaac.ml_archive" = {}  # needed for torch

[[python.module]]
name = "omni.isaac.cloner"

[[test]]
dependencies = [
    "omni.physx",
    "omni.isaac.core",
    "omni.isaac.nucleus", # test only
]
