[manipulators]
reloadable = true
order = 0

[package]
version = "2.1.0"
category = "Simulation"
title = "Isaac Sim Manipulators"
description = "Manipulators"
authors = ["NVIDIA"]
repository = ""
keywords = ["isaac", "manipulators"]
changelog = "docs/CHANGELOG.md"
readme = "docs/README.md"
icon = "data/icon.png"
preview_image = "data/preview.png"
writeTarget.kit = true

[dependencies]
"omni.isaac.core" = {}
"omni.isaac.core_nodes" = {}
"omni.isaac.surface_gripper" = {}

[[python.module]]
name = "omni.isaac.manipulators"

[[python.module]]
name = "omni.isaac.manipulators.tests"

[fswatcher.patterns]
include = ["*.ogn", "*.py"]
exclude = ["Ogn*Database.py"]

[[test]]
timeout = 1200

stdoutFailPatterns.exclude = [
    "*[Error] [omni.graph.core.plugin] /TestGraph/Template_omni_isaac_manipulators_IsaacGripperController: [/TestGraph] OmniGraph Error: No robot prim found for the articulation controller*",
]