[package]
category = "Simulation"
authors = ["NVIDIA"]
title = "Physics Bundle"
description = "Omniverse physics bundle extension."
repository = ""
keywords = ["physics", "physx", "vehicle"]

version = "106.0.20"

icon = "data/icon.png"
preview_image = "data/preview.png"
changelog="docs/CHANGELOG.md"
readme  = "docs/README.md"
support_level = "Example"

[package.writeTarget]
kit = true
python = true
usd = true

[dependencies]
"omni.physx" = { version = "106.0.20", exact = true }
"omni.physx.stageupdate" = { version = "106.0.20", exact = true }
"omni.physx.ui" = { version = "106.0.20", exact = true }
"omni.physx.vehicle" = { version = "106.0.20", exact = true }
"omni.physx.demos" = { version = "106.0.20", exact = true }
"omni.kit.property.physx" = { version = "106.0.20", exact = true }
"omni.usdphysics" = { version = "106.0.20", exact = true }
"omni.usdphysics.ui" = { version = "106.0.20", exact = true }
"omni.physx.cct" = { version = "106.0.20", exact = true }
"omni.physx.commands" = { version = "106.0.20", exact = true }
"omni.physx.camera" = { version = "106.0.20", exact = true }
"omni.usd.schema.forcefield" = { version = "106.0.20", exact = true }
"omni.physx.supportui" = { version = "106.0.20", exact = true }
"omni.physx.graph" = { version = "106.0.20", exact = true }
"omni.physx.telemetry" = { version = "106.0.20", exact = true }

[[test]]
dependencies = ["omni.kit.renderer.core", "omni.kit.test"]

waiver = "PhysX tests are running in a separate CI pipeline. Tests are in separate extensions."
