[manipulators]
reloadable = true
order = 0

[package]
version = "1.2.1"
category = "Simulation"
title = "Isaac Sim Manipulators UI"
description = "Manipulators"
authors = ["NVIDIA"]
repository = ""
keywords = ["isaac", "manipulators", "ui"]
changelog = "docs/CHANGELOG.md"
readme = "docs/README.md"
icon = "data/icon.png"
preview_image = "data/preview.png"
writeTarget.kit = true

[dependencies]
"omni.isaac.core" = {}
"omni.isaac.manipulators" = {}

[[python.module]]
name = "omni.isaac.manipulators.ui"