[core]
reloadable = true
order = 0

[package]
version = "1.0.1"
category = "Simulation"
title = "Isaac Sim Range Sensor UI components"
description = "UI components for the Range Sensor extension"
authors = ["NVIDIA"]
repository = ""
keywords = ["isaac", "physics", "sensor", "lidar", "ui"]
changelog = "docs/CHANGELOG.md"
readme = "docs/README.md"
preview_image = "data/preview.png"
icon = "data/icon.png"
writeTarget.kit = true

[dependencies]
"omni.kit.uiapp" = {}
"omni.kit.menu.utils" = {}
"omni.usd.schema.isaac" = {}
"omni.isaac.ui" = {}
"omni.isaac.core" = {}
"omni.isaac.range_sensor" = {}
"omni.kit.context_menu" = {}

[[python.module]]
name = "omni.isaac.range_sensor.ui"
