[package]
category = "Internal"
authors = ["NVIDIA"]
title = "PhysX Mini Tests"
description="minimal tests for omni.physx targeted for non-gpu configurations"
repository = ""
keywords = ["physx", "tests"]

support_level = "Internal"

[dependencies]
"omni.physx" = {}
"omni.kit.test" = {}
"omni.kit.stage_templates" = {}

[[python.module]]
name = "omni.physxtestsmini"

[[test]]
dependencies = [
]
args = [
    "--/renderer/enabled='placeholder'",
    "--/renderer/active=false",
    "--/app/file/ignoreUnsavedOnExit=true",
    "--no-window",
    "--/app/profilerBackend=\"\"",
    "--/omni.kit.plugin/syncUsdLoads=true",
]
timeout = 600
pyCoverageFilter = ["omni.physx"]
pyCoverageThreshold = 0
stdoutFailPatterns.exclude = [
    "*[gpu.foundation.plugin] No device could be created. Some known system issues:*",
    "*[omni.gpu_foundation_factory.plugin] Failed to create GPU foundation devices for compatibilityMode*",
    "*[omni.kit.renderer.plugin] GPU Foundation is not initialized!*",
    "*[carb.cudainterop.plugin] Failed to query CUDA device count.*",
    "*[gpu.foundation.plugin] Local device index*out of range*",
    "*[carb.cudainterop.plugin] CUDA error 35: cudaErrorInsufficientDriver - CUDA driver version is insufficient for CUDA runtime version)*",
    "*[carb.graphics-vulkan.plugin] VkResult: ERROR_INCOMPATIBLE_DRIVER*",
    "*[carb.graphics-vulkan.plugin] vkCreateInstance failed. Vulkan 1.1 is not supported, or your driver requires an update.*",
    "*[gpu.foundation.plugin] carb::graphics::createInstance failed.*",
    "*failed to load native plugin*carb.graphics-vulkan.plugin.dll*",           # ignore to not always fail on Win machines without a gpu
    "*Could not load the dynamic library*carb.graphics-vulkan.plugin.dll*",     # ignore to not always fail on Win machines without a gpu
    "*Could not load libcuda.so: libcuda.so: cannot open shared object file: No such file or directory*", # ignore to not always fail on linux without a gpu
]
