[package]
version = "0.13.2"
category = "Setup"
title = "Isaac Sim Setup"
description = "This Extension does the setup of the Isaac Sim App"
authors = ["NVIDIA"]
repository = ""
keywords = ["isaac"]
changelog = "docs/CHANGELOG.md"
readme = "docs/README.md"
icon = "data/omni.isaac.sim.png"
preview_image = "data/preview.png"
toggleable = false

[dependencies]
"omni.usd" = {}
"omni.ui" = {}
"omni.kit.stage_templates" = {}
"omni.kit.window.title" = {}
"omni.isaac.version" = {}
"omni.kit.quicklayout" = {}
"omni.kit.viewport.utility" = {}
"omni.kit.window.property" = {}
"omni.kit.menu.common" = {}

[[python.module]]
name = "omni.isaac.app.setup"

[settings]
isaac.startup.create_new_stage = true # create a new stage on startup
[settings."filter:platform"."windows-x86_64"]
isaac.startup.ros_bridge_extension = ""
[settings."filter:platform"."linux-x86_64"]
isaac.startup.ros_bridge_extension = "omni.isaac.ros2_bridge"

[[test]]
dependencies = [
   "omni.rtx.settings.core", "omni.pip.cloud", "omni.replicator.core"
]

stdoutFailPatterns.exclude = [
    "*[omni.isaac.ros2_bridge.plugin]*", # Ada multi gpu doesn't support this yet
    "*[omni.isaac.ros2_bridge.scripts.extension]*", # Ada multi gpu doesn't support this yet
]
