import carb
from . import autogenerated_telemetry_module


class OmniPhysXTelemetry:
    debug_logging: bool = True  # echoes telemetry events on the carb.log_info
    telemetry_is_enabled: bool = False  # persistent-setting controlled variable to actually do telemetry or not

    @staticmethod
    def log_omni_physx_zerog_activated():
        """ Logs whether ZG is activated (ZG mode is entered) """
        if OmniPhysXTelemetry.telemetry_is_enabled:
            autogenerated_telemetry_module.log_omni_physx_zerog_activated_send_event()
            if OmniPhysXTelemetry.debug_logging:
                carb.log_info("OmniPhysXTelemetry: log_omni_physx_zerog_activated")

    @staticmethod
    def log_omni_physx_stage_apis(apis_found_on_prims: str):
        """ Logs USD Physics APIs found by FSD on stage load """
        if OmniPhysXTelemetry.telemetry_is_enabled:
            autogenerated_telemetry_module.log_omni_physx_stage_apis_send_event(apis_found_on_prims)
            if OmniPhysXTelemetry.debug_logging:
                carb.log_info(f"OmniPhysXTelemetry: log_omni_physx_stage_apis({apis_found_on_prims})")
