[core]
reloadable = true
order = 0

[package]
version = "1.1.0"
category = "Simulation"
title = "Isaac Sim Debug Drawing"
description = "Persistent Debug Drawing Helpers"
authors = ["NVIDIA"]
repository = ""
keywords = ["isaac", "physics", "inspect",]
changelog = "docs/CHANGELOG.md"
readme = "docs/README.md"
preview_image = "data/preview.png"
icon = "data/icon.png"
writeTarget.kit = true

# Other extensions that must be loaded before this one
[dependencies]
"omni.graph" = {}
"omni.graph.tools" = {}
# needed to access drawing interfaces:
"omni.kit.renderer.core" = {}
"omni.kit.viewport.window" = {}
"omni.hydra.rtx" = {}
# The generated tests will make use of these modules
"omni.usd" = {}
"omni.kit.async_engine" = {}

[[python.module]]
name = "omni.isaac.debug_draw"

[[python.module]]
name = "omni.isaac.debug_draw.tests"

# Watch the .ogn files for hot reloading (only for Python files)
[fswatcher.patterns]
include = ["*.ogn", "*.py"]
exclude = ["Ogn*Database.py"]


[[native.plugin]]
path = "bin/*.plugin"
recursive = false

[[test]]
stdoutFailPatterns.exclude = [
 "*[Error] [omni.graph.core.plugin] /TestGraph/Template_omni_isaac_debug_draw_IsaacXPrimAxisVisualizer: [/TestGraph] Omnigraph Error: no input prim found for visualization*",
 "*[Error] [omni.graph.core.plugin] /TestGraph/Template_omni_isaac_debug_draw_IsaacXPrimRadiusVisualizer: [/TestGraph] Omnigraph Error: no input prim found for visualization*"

]
