[package]
title = "Physics Schema Plugin"
description="Handles loading of USD PhysicsSchema."
repository = ""
keywords = ["physics"]
category = "simulation"

version = "106.0.20"
authors = ["NVIDIA"]

icon = "data/icon.png"
preview_image = "data/preview.png"
changelog="docs/CHANGELOG.md"
readme  = "docs/README.md"
support_level = "Enterprise"

[package.writeTarget]
kit = true
python = true
usd = true

[dependencies]
"omni.usd.libs" = { }

[[native.plugin]]
path = "bin/*.plugin"

[[test]]
waiver = "PhysX tests are running in a separate CI pipeline. Tests are in separate extensions."