[package]
title = "PhysX SupportUI"
description="PhysX Simplified UI."
authors = ["NVIDIA"]
icon = "icons/icon.png"
preview_image = "icons/preview_image.png"
repository = ""
keywords = ["physx", "physics", "streamlinedux", "ux", "supportui", "simplifiedui", "babyui", "inspector"]
category = "Simulation"

version = "106.0.20"

changelog="docs/CHANGELOG.md"
readme  = "docs/README.md"

support_level = "Example"

[package.writeTarget]
kit = true
python = true
usd = true

[dependencies]
"omni.ui" = {}
"omni.physx" = {}
"omni.physx.ui" = {}
"omni.physx.commands" = {}
"omni.physx.tests" = {optional=true}
"omni.debugdraw" = {}
"omni.kit.viewport.utility" = {} 
"omni.kit.viewport.registry" = {}
"omni.kit.window.preferences" = {}
"omni.kit.window.toolbar" = {}
"omni.kit.widget.stage" = {} # because of rb selection mode
"omni.kit.widget.layers" = {} # because of rb selection mode
"omni.kit.context_menu" = {}
"omni.kit.widget.settings" = {}
"omni.kit.window.popup_dialog" = {}
"omni.usd" = {}
"omni.kit.commands" = {}
"omni.kit.notification_manager" = {}
"omni.kit.manipulator.prim" = {}
"omni.kit.manipulator.selector" = {}
"omni.kit.manipulator.selection" = {}
"usdrt.scenegraph" = {}

[[python.module]]
name = "omni.physxsupportui"

[[native.plugin]]
path = "bin/*.plugin"

[[test]]
dependencies = [
    "omni.assets.plugins",
    "omni.kit.renderer.core",
    "omni.physx.tests",
    "omni.physx.tests.visual",
    "omni.physx.ui",
    "omni.kit.viewport.window",
    "omni.kit.ui_test",
    "omni.kit.property.physx",
    "omni.hydra.rtx",
]
args = [
    "--/app/window/width=1280",
    "--/app/window/height=1024",
    "--/app/asyncRendering=false",
    "--no-window",
    "--/renderer/multiGpu/autoEnable=false",
    "--/renderer/multiGpu/enabled=false",
    "--/renderer/debug/validation/enabled=false",
    "--/omni.kit.plugin/syncUsdLoads=true",
]
timeout = 1200
waiver = "PhysX tests are running in a separate CI pipeline. Tests are in separate extensions." # FIXME: this is needed for Kit tests to go through

[settings]
persistent.exts."omni.kit.manipulator.selector".orders."omni.physxsupportui" = -10  # Add a setting to define the priority of this manipulator