[package]
title = "Omniverse PhysX PVD plugin"
description="Omniverse PhysX PVD plugin."
changelog="docs/CHANGELOG.md"
repository = ""
keywords = ["physics", "physx", "pvd"]
category = "Simulation"
authors = ["NVIDIA"]

version = "106.0.20"

icon = "data/icon.png"
preview_image = "data/preview.png"
changelog="docs/CHANGELOG.md"
readme  = "docs/README.md"
support_level = "Example"

[package.writeTarget]
kit = true
python = true
usd = true

[[python.module]]
name = "omni.physxpvd"

[[native.plugin]]
path = "bin/*.plugin"

[dependencies]
"omni.ui" = {}
"omni.timeline" = {}
"omni.physx" = {}
"omni.physx.ui" = {}
"omni.debugdraw" = {}
"omni.kit.menu.utils" = {}
"omni.kit.window.toolbar" = {}
"omni.kit.widget.stage" = {}
"omni.kit.widget.settings" = {}
"omni.kit.property.physx" = {}
"omni.kit.tool.asset_importer" = {}
"omni.kit.timeline.minibar" = {}
"omni.physx.tests" = {optional=true}

[settings]
exts."omni.kit.timeline.minibar".speedupEnable = false

[[test]]
dependencies = [
   "omni.kit.renderer.core",
   "omni.physx.tests",
]
