[package]
version = "0.3.4"
category = "Setup"
title = "Isaac Sim Assets Check"
description = "This Extension checks if the assets are updated."
authors = ["NVIDIA"]
repository = ""
keywords = ["isaac"]
changelog = "docs/CHANGELOG.md"
readme = "docs/README.md"
icon = "data/icon.png"
preview_image = "data/preview.png"
toggleable = false

[dependencies]
"omni.usd" = {}
"omni.ui" = { order = -100 }

# Isaac Sim Core Extensions
"omni.isaac.core" = {}
"omni.isaac.nucleus" = {}

[[python.module]]
name = "omni.isaac.assets_check"


