[package]
# Semantic Versionning is used: https://semver.org/
version = "1.1.0"

# Lists people or organizations that are considered the "authors" of the package.
authors = ["NVIDIA"]

# The title and description fields are primarily for displaying extension info in UI
title = "Isaac Sim About Window"
description="Show application/build information."

# URL of the extension source repository.
repository = ""

# Preview image. Folder named "data" automatically goes in git lfs (see .gitattributes file).
preview_image = "data/preview.png"
icon = "data/icon.png"
readme = "docs/README.md"
# One of categories for UI.
category = "Internal"

# Keywords for the extension
keywords = ["kit"]

# https://keepachangelog.com/en/1.0.0/
changelog="docs/CHANGELOG.md"

[dependencies]
"omni.ui" = {}
"omni.client" = {}
"omni.kit.uiapp" = {}
"omni.kit.renderer.core" = {}
"omni.kit.renderer.capture" = {}
"omni.kit.pip_archive" = {} # pulls in pyperclip
"omni.isaac.version" = {}

[[python.module]]
name = "omni.isaac.window.about"

[test]
dependencies = [
    "omni.kit.uiapp",
    "omni.kit.renderer.core",
    "omni.kit.renderer.capture",
]

stdoutFailPatterns.include = []
stdoutFailPatterns.exclude = []
