[core]
reloadable = true
order = 0

[package]
version = "0.1.3"
category = "Simulation"
title = "Isaac Sim Example Nodes"
description = "This extension adds Omnigraph example nodes for Isaac Sim"
authors = ["NVIDIA"]
repository = ""
keywords = ["isaac", "omnigraph", "examples"]
changelog = "docs/CHANGELOG.md"
readme = "docs/README.md"
icon = "data/icon.png"
preview_image = "data/preview.png"
writeTarget.kit = true

[dependencies]
"omni.physx" = {}
"omni.isaac.core" = {}
"omni.isaac.core_nodes" = {}
"omni.isaac.ui" = {}
"omni.isaac.franka" = {}
"omni.isaac.universal_robots" = {}
"omni.isaac.core_archive" = {} # scipy, osqp, qdldl
"omni.graph" = {}
"omni.graph.tools" = {}

[[python.module]]
name = "omni.isaac.examples_nodes"

[[python.module]]
name = "omni.isaac.examples_nodes.tests"

[fswatcher.patterns]
include = ["*.ogn", "*.py"]
exclude = ["Ogn*Database.py"]

[[test]]
timeout = 1200

