[core]
reloadable = true
order = 0

[package]
version = "0.1.9"
category = "Simulation"
title = "Articulation Inspector"
description = "This extension can inspect and modify the properties of an articulation."
authors = ["NVIDIA"]
repository = ""
keywords = ["isaac", "physics", "analyze", "inspect"]
changelog = "docs/CHANGELOG.md"
readme = "docs/README.md"
icon = "data/icon.png"
preview_image = "data/preview.png"
writeTarget.kit = true


[deprecation]
warning = "Extension deprecated since Isaac Sim 4.0.0. Replaced by omni.physx.inspector"


[dependencies]
"omni.physx" = {}
"omni.isaac.core" = {}
"omni.isaac.dynamic_control" = {}
"omni.isaac.ui" = {}

[[python.module]]
name = "omni.isaac.articulation_inspector"

