[core]
reloadable = true
order = 0

[package]
version = "0.4.1"
category = "Simulation"
title = "Simulated Environments for use in Isaac Sim"
description = "Extension for programming simple environments for robots"
authors = ["NVIDIA"]
repository = ""
keywords = ["isaac", "samples", "environments"]
changelog = "docs/CHANGELOG.md"
readme = "docs/README.md"
icon = "data/icon.png"
preview_image = "data/preview.png"

[dependencies]
"omni.isaac.core" = {}

[[python.module]]
name = "omni.isaac.benchmark_environments"

[[python.module]]
name = "omni.isaac.benchmark_environments.tests"

[deprecation]
warning = "Extension deprecated since Isaac Sim 4.0.0"