[package]
title = "PhysX UI"
description="Adds GUI elements for physics authoring."
repository = ""
keywords = ["physics", "physx", "ui"]
category = "simulation"
authors = ["NVIDIA"]

version = "106.0.20"

icon = "data/icon.png"
preview_image = "data/preview.png"
changelog="docs/CHANGELOG.md"
readme  = "docs/README.md"
support_level = "Example"

[package.writeTarget]
kit = true
python = true
usd = true

[dependencies]
"omni.ui" = {}
"omni.usdphysics.ui" = {}
"omni.physx" = {}
"omni.timeline" = {}
"omni.debugdraw" = {}
"omni.kit.window.property" = {}
"omni.kit.viewport.utility" = {}
"omni.kit.window.preferences" = {}
"omni.kit.context_menu" = {}
"omni.kit.widget.settings" = {}
"omni.kit.window.popup_dialog" = {}
"omni.kit.property.usd" = {}
"omni.usd" = {}
"omni.kit.commands" = {}
"omni.physx.commands" = {}
"omni.physx.stageupdate" = {}
"omni.kit.notification_manager" = {}
"omni.client" = {}
"omni.ui.scene" = {}
"omni.kit.actions.core" = {}
"omni.kit.manipulator.tool.snap" = {}
"omni.kit.manipulator.transform" = {}
"usdrt.scenegraph" = {}
"omni.kit.hotkeys.core" = { optional = true }
"omni.kit.viewport.window" = {}
"omni.kit.menu.utils" = {}

[[python.module]]
name = "omni.physxui"

[[native.plugin]]
path = "bin/*.plugin"

[[test]]
dependencies = [
    "omni.kit.renderer.core",
    "omni.kit.stage_templates",
    "omni.kit.ui_test",
    "omni.physx.tests",    
]

args = [
    "--/physics/developmentMode=true",
    "--/app/file/ignoreUnsavedOnExit=true",
    "--no-window"
]
waiver = "PhysX tests are running in a separate CI pipeline. Tests are in separate extensions."
