[core]
reloadable = true
order = 0

[package]
version = "1.1.0"
category = "Other"
title = "Isaac Sim Version"
description = "Isaac Sim Version"
authors = ["NVIDIA"]
repository = ""
keywords = ["isaac"]
changelog = "docs/CHANGELOG.md"
readme = "docs/README.md"
preview_image = "data/preview.png"
icon = "data/icon.png"

[dependencies]


[[python.module]]
name = "omni.isaac.version"

[[python.module]]
name = "omni.isaac.version.tests"

[[test]]
dependencies = ["omni.kit.test"]
