[package]
title = "KeyValueDatabase"
display_name = "KeyValueDatabase extension"
description = "KeyValueDatabase extension"

version = "106.0.20"

authors = ["NVIDIA"]
repository = ""
keywords = ["database"]
category = "Internal"
icon = "data/icon.png"
preview_image = "data/preview.png"
changelog="docs/CHANGELOG.md"
readme  = "docs/README.md"
support_level = "Enterprise"

[package.writeTarget]
kit = true
python = true
usd = true

[dependencies]

[[python.module]]
name = "omni.kvdb"

[[native.plugin]]
path = "bin/*.plugin"

[[test]]
waiver = "PhysX tests are running in a separate CI pipeline. Tests are in separate extensions."