[package]
title = "Local cache"
display_name = "Local Cache"
description = "Local Cache"

authors = ["NVIDIA"]
repository = ""
keywords = ["database"]
category = "Internal"

version = "106.0.20"
icon = "data/icon.png"
preview_image = "data/preview.png"
changelog="docs/CHANGELOG.md"
readme  = "docs/README.md"
support_level = "Enterprise"

[package.writeTarget]
kit = true
python = true
usd = true

[dependencies]
"omni.kvdb" = { version = "106.0.20", exact = true }

[[python.module]]
name = "omni.localcache"

[[native.plugin]]
path = "bin/*.plugin"

[[test]]
waiver = "PhysX tests are running in a separate CI pipeline. Tests are in separate extensions."
