class ZeroGravityConstants:
    EXTENSION_DISPLAY_NAME = "Zero Gravity"


class ColliderTypes:
    STATIC_COLLIDER_SIMPLIFICATION_TYPE_TRIANGLE_MESH = 0
    STATIC_COLLIDER_SIMPLIFICATION_TYPE_MESH_SIMPLIFICATION = 1
    DYNAMIC_COLLIDER_SIMPLIFICATION_TYPE_CONVEX_HULL = 0
    DYNAMIC_COLLIDER_SIMPLIFICATION_TYPE_CONVEX_DECOMPOSITION = 1

