[core]
reloadable = true
order = 0

[package]
version = "0.1.0"
category = "Internal"
title = "Isaac Sim Common Includes"
description = "Extension containing common isaac sim headers"
authors = ["NVIDIA"]
repository = ""
keywords = ["isaac", "test", "doctest", "docstrings"]
changelog = "docs/CHANGELOG.md"
readme = "docs/README.md"
preview_image = "data/preview.png"
icon = "data/icon.png"

