[package]
title = "PhysX Fabric"
description="Omni PhysX Fabric output"
repository = ""
keywords = ["physics", "physx", "fabric"]
category = "Simulation"

version = "106.0.20"
authors = ["NVIDIA"]

icon = "data/icon.png"
preview_image = "data/preview.png"
changelog="docs/CHANGELOG.md"
readme  = "docs/README.md"
support_level = "Example"

[package.writeTarget]
kit = true
python = true
usd = true


[dependencies]
"omni.physx" = { }
"usdrt.scenegraph" = {}
"omni.graph.core" = {optional=true}
"omni.ui" = {optional=true}
"omni.kit.window.preferences" = {optional=true}
"omni.kit.widget.settings" = {optional=true}


[[python.module]]
name = "omni.physxfabric"

[[native.plugin]]
path = "bin/*.plugin"

[[test]]
dependencies = [
]
waiver = "PhysX tests are running in a separate CI pipeline. Tests are in separate extensions."
