[package]
title = "PhysX Foundation"
description="PhysX 5 foundation."

version = "106.0.20"
authors = ["NVIDIA"]

repository = ""
keywords = ["physics", "physx", "foundation"]
category = "simulation"

icon = "data/icon.png"
preview_image = "data/preview.png"
changelog="docs/CHANGELOG.md"
readme  = "docs/README.md"
support_level = "Enterprise"

[package.writeTarget]
kit = true
python = true
usd = true

[dependencies]

[[native.plugin]]
path = "bin/omni.physx.foundation.plugin"

[[test]]
waiver = "PhysX tests are running in a separate CI pipeline. Tests are in separate extensions."