[package]
version = "106.0.20"
authors = ["NVIDIA"]

title = "PhysX Tensor API Implementation"
description="PhysX Tensor API Implementation"
repository = ""
keywords = ["omniverse", "kit", "physics", "physx", "tensors"]
category = "simulation"

icon = "data/icon.png"
preview_image = "data/preview.png"
changelog="docs/CHANGELOG.md"
readme  = "docs/README.md"
support_level = "Example"

[package.writeTarget]
kit = true
python = true
usd = true

[dependencies]
"omni.physics.tensors" = {}
"omni.physx" = {}
"omni.usd" = {}

[[native.plugin]]
path = "bin/*.plugin"
recursive = false
