[core]
reloadable = true
order = 0

[package]
version = "0.5.0"
category = "Rendering"
title = "Isaac Sim Asset Browser"
description = "A browser for Isaac Sim assets"
authors = ["NVIDIA"]
repository = ""
keywords = ["isaac", "browser", "asset"]
changelog = "docs/CHANGELOG.md"
readme = "docs/README.md"
preview_image = "data/preview.png"
icon = "data/icon.svg"
feature = true
# writeTarget.kit = true

[dependencies]
"omni.kit.browser.folder.core" = {}
"omni.kit.commands" = {}
"omni.kit.menu.utils" = {}
"omni.usd" = {}
"omni.kit.viewport.utility" = { }
"omni.kit.tool.collect" = { optional=true }
"omni.kit.menu.stage" = { optional=true }
"omni.kit.clipboard" = { optional=true }


# Main python module this extension provides, it will be publicly available as "import omni.isaac.asset_browser".
[[python.module]]
name = "omni.isaac.asset_browser"

[settings]
exts."omni.isaac.asset_browser".folders = [
    "http://omniverse-content-production.s3-us-west-2.amazonaws.com/Assets/Isaac/4.1/Isaac/Robots",
    "http://omniverse-content-production.s3-us-west-2.amazonaws.com/Assets/Isaac/4.1/Isaac/People",
    "http://omniverse-content-production.s3-us-west-2.amazonaws.com/Assets/Isaac/4.1/Isaac/IsaacLab",
    "http://omniverse-content-production.s3-us-west-2.amazonaws.com/Assets/Isaac/4.1/Isaac/Props",
    "http://omniverse-content-production.s3-us-west-2.amazonaws.com/Assets/Isaac/4.1/Isaac/Environments",
    "http://omniverse-content-production.s3-us-west-2.amazonaws.com/Assets/Isaac/4.1/Isaac/Materials",
    "http://omniverse-content-production.s3-us-west-2.amazonaws.com/Assets/Isaac/4.1/Isaac/Samples",
    "http://omniverse-content-production.s3-us-west-2.amazonaws.com/Assets/Isaac/4.1/Isaac/Sensors",
]
exts."omni.isaac.asset_browser".instanceable = []
exts."omni.isaac.asset_browser".data.timeout = 10
exts."omni.isaac.asset_browser".visible_after_startup = true

[[trigger]]
menu.name = "Window/Browsers/Isaac"
menu.window = "Isaac Assets (Beta)"


[[test]]
dependencies = [
    "omni.kit.renderer.core",
    "omni.kit.renderer.capture",
    "omni.kit.tool.collect",
    "omni.kit.menu.stage",
    "omni.kit.ui_test",
    "omni.usd",
    "omni.kit.clipboard",
    "omni.kit.browser.asset",
]

args = [
    "--/app/window/dpiScaleOverride=1.0",
    "--/app/window/scaleToMonitor=false",
    "--/app/menu/legacy_mode=false",
    "--/exts/omni.kit.browser.asset/folders/0='http://omniverse-content-production.s3-us-west-2.amazonaws.com/Assets/Isaac/4.1/Isaac/Robots'",
    "--/exts/omni.kit.browser.asset/folders/1=''",
    "--/exts/omni.kit.browser.asset/folders/2=''",
    "--/exts/omni.kit.browser.asset/visible_after_startup=true",
]

[documentation]
pages = [
    "docs/Overview.md",
    "docs/CHANGELOG.md",
]
