[package]
title = "Physics Schema Tests"
description="Tests loading of PhysicsSchema."
repository = ""
keywords = ["physics", "tests"]
category = "simulation"

version = "106.0.0"
authors = ["NVIDIA"]

icon = "data/icon.png"
preview_image = "data/preview.png"
changelog="docs/CHANGELOG.md"
readme  = "docs/README.md"
support_level = "Internal"

[package.writeTarget]
kit = true
python = true
usd = true

[dependencies]
"omni.kit.stage_templates" = {}
"omni.usdphysics" = {}
"omni.physx.tests" = {}

[[python.module]]
name = "omni.usdphysicstests"

[[native.plugin]]
path = "bin/*.plugin"

[[test]]
dependencies = [
]
pyCoverageFilter = ["omni.usdphysics"]
pyCoverageThreshold = 0
