[package]
title = "OmniPhysX StageUpdate"
description="OmniPhysX StageUpdate Connection."
repository = ""
keywords = ["physics", "physx"]
category = "Simulation"
authors = ["NVIDIA"]

version = "106.0.20"

icon = "data/icon.png"
preview_image = "data/preview.png"
changelog="docs/CHANGELOG.md"
readme  = "docs/README.md"

support_level = "Enterprise"

[package.writeTarget]
kit = true
python = true
usd = true

[dependencies]
"omni.physx" = { version = "106.0.20", exact = true }
"omni.usd" = { }
"omni.timeline.live_session" = { optional = true }
"omni.kit.usd.layers" = { optional = true }
"omni.ui" = {optional=true}

[[python.module]]
name = "omni.physxstageupdate"

[[native.plugin]]
path = "bin/*.plugin"

[[test]]
dependencies = [
   "omni.physx.tests",
   "omni.hydra.rtx",
   "omni.kit.viewport.window",
]

timeout = 1200
args = [
   "--/app/file/ignoreUnsavedOnExit=true",
   "--no-window",
]
waiver = "PhysX tests are running in a separate CI pipeline. Tests are in separate extensions." # FIXME: this is needed for Kit tests to go through
